version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1

executors:
  our-node:
    machine: true
    resource_class: runnerpoc/test

  ubuntu-browsers:
    docker:
      - image: cimg/python:3.9-browsers

jobs:
  runner:
    executor: our-node
    steps:
      - run: echo "Hi I'm on Runners!"

  runner2:
    executor: our-node
    steps:
      - run: echo "I reused the executor!"

  browsers:
    executor: ubuntu-browsers
    steps:
      - browser-tools/install-browser-tools
      - run: |
          python --version
          node --version
          java --version
          google-chrome --version
          firefox --version
      - run: pip freeze

workflows:
  testing:
    jobs:
      - runner
      - runner2
