version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1

executors:
  our-node:
    machine: true
    resource_class: runnerpoc/test

  ubuntu-browsers:
    docker:
      - image: cimg/python:3.9-browsers

  configurable-python:
    parameters:
      version:
        description: "python version tag"
        default: "3.9"
        type: string
    docker:
      - image: cimg/python:<<parameters.version>>

jobs:
  runner:
    executor: our-node
    steps:
      - run: echo "Hi I'm on Runners!"

  runner2:
    executor: our-node
    steps:
      - run: echo "I reused the executor!"

  browsers:
    executor: ubuntu-browsers
    steps:
      - browser-tools/install-browser-tools
      - run: |
          python --version
          node --version
          java --version
          google-chrome --version
          firefox --version
      - run: pip freeze

  python-version:
    parameters:
      version:
        description: "python version tag"
        default: "3.9"
        type: string
    executor:
      name: configurable-python
      version: <<parameters.version>>
    steps:
      - run: python --version

workflows:
  testing:
    jobs:
      - runner
      - runner2
      - browsers
      - python-version:
          matrix:
            parameters:
              version:
                - 2.7
                - 3.6
                - 3.9
