version: 2.1

executors:
  runner:
    machine: true
    resource_class: runnerpoc/test

workflows:
  test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - typecheck:
          requires:
            - build
      - unit-test:
          requires:
            - build
      - e2e-test:
          requires:
            - build
      - clean:
          requires:
            - lint
            - typecheck
            - unit-test
            - e2e-test

commands:
  run-in-docker:
    description: 'Runs the given command in a docker container'
    parameters:
      COMMAND:
        type: string
        description: 'The command to run in Docker'
      NAME:
        type: string
        description: 'The name to use when running in Docker'
    steps:
      - run: docker-compose run --name "<< pipeline.id >><< parameters.NAME >>" --rm cli << parameters.COMMAND >>

jobs:
  build:
    executor: runner
    steps:
      - checkout
      - run: 
          command: make build-docker
          environment:
            VERSION: "0.0.0"
      - run-in-docker:
          COMMAND: 'make build'
          NAME: 'build'
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor: runner
    steps:
      - attach_workspace:
          at: .
      - run-in-docker:
          COMMAND: 'make lint'
          NAME: 'lint'

  typecheck:
    executor: runner
    steps:
      - attach_workspace:
          at: .
      - run-in-docker:
          COMMAND: 'make typecheck'
          NAME: 'typecheck'

  unit-test:
    executor: runner
    steps:
      - attach_workspace:
          at: .
      - run-in-docker:
          COMMAND: 'make run-tests'
          NAME: 'unittest'

  e2e-test:
    executor: runner
    steps:
      - attach_workspace:
          at: .
      - run-in-docker:
          COMMAND: 'make run-e2e-tests'
          NAME: 'e2etest'

  clean:
    executor: runner
    steps:
      - attach_workspace:
          at: .
      - run: make clean
